# Generated by Django 2.2.24 on 2021-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0003_auto_20211103_2016'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(blank=True, to='Clase.Clase'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
