# Generated by Django 2.2.24 on 2021-11-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='clase',
            new_name='estudiante',
        ),
    ]
