# Generated by Django 2.2.24 on 2021-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0002_auto_20211103_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='Asignatura',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='Dias',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='clase',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='horario_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='horario_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClasesEstudiantes',
        ),
    ]
